workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.agregmaster.app
    integrations:
      app_store_connect: Agreg Master
    scripts:
      - name: Set up Firebase config for iOS
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > "$CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist"

      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Flutter build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
      groups:
        - keystore_credentials
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/agreg-master-release.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=agreg-master-release.jks
          EOF

      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Flutter build AAB
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
