name: agreg_master
description: Application de fiches de cours pour l'agrégation (Algèbre, Analyse).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  flutter_markdown_latex: ^0.3.4
  flutter_math_fork: ^0.7.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^7.2.2
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fiches/
    - assets/fiches/algebre/
    - assets/fiches/analyse/
    - assets/fiches/probabilites/      
    - assets/fiches/geometrie/ 
    - assets/data/quiz.json 
    - assets/glossaire.json

    
